### PR TITLE
Signup

### PR DESCRIPTION
**Pull request by dokdek**
Added signup feature and a basis for auth via JWT. Currently only username is saved with the token, can be extended for later as needed

### CODE REVIEW

**Comment by dokdek** [comment]
Please review @HappyNimbus

**Comment by HappyNimbus** [comment]
Looks good, I am using this as a skeleton to work on itemsDB

**Review by HappyNimbus — APPROVED** [review]
Solid

**Review by HappyNimbus — APPROVED** [review]
Approved again? 💀

**Pull request merged**
